export const rutas = {
    LOGIN: "/",
    UNAUTHORIZED: "/unauthorized",
    DOCENTE: "/docente",
    DOC_INI: "/docente/iniciando",
    DOC_ECU: "/docente/encurso",
    DOC_CUR: "/docente/curso",
    DOC_ASI: "/docente/asignatura",
    ESTUDIANTE: "/estudiante",
    EST_ING: "/estudiante/ingreso",
    EST_CUR: "/estudiante/curso",
    EST_ENT: "/estudiante/entrando",
    EST_MAT: "/estudiante/matricula",
    ADMIN: "/admin",
    ADM_ASI: "/admin/asignatura",
    ADM_CUR: "/admin/curso",
    ADM_DEP: "/admin/departamento",
    ADM_EST: "/admin/estudiante",
    ADM_MAT: "/admin/matricula",
    ADM_PER: "/admin/periodo",
    ADM_PLN: "/admin/plan",
    ADM_DOC: "/admin/docente",
    ADM_PRG: "/admin/programa",
    ADM_SAL: "/admin/salon",
    PENDIENTE: "/pendiente"
}